# Generated by Django 5.1.3 on 2025-01-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_scolastici', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='titolo',
            field=models.CharField(max_length=40),
        ),
    ]
