# Generated by Django 5.1.3 on 2025-01-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articolo_options_alter_giornalista_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data',
            field=models.DateField(blank=True),
        ),
    ]
